-- NAME -> ANIMAL_NAME
-- DATETIME -> DATE_TIME

-- condition: 보호소에 가장 먼저 들어온 동물은 한 마리인 경우만 테스트 케이스로 주어집니다.

/*
SELECT ANIMAL_NAME FROM ANIMAL_INS
ORDER BY DATE_TIME ASC
LIMIT 1;
*/

SELECT ANIMAL_NAME FROM ANIMAL_INS
WHERE DATE_TIME = (SELECT MIN(DATE_TIME) FROM ANIMAL_INS);