-- SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS ANIMAL_COUNT
-- FROM ANIMAL_INS
-- WHERE ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog'
-- GROUP BY ANIMAL_TYPE
-- ORDER BY ANIMAL_TYPE ASC;

-- SELECT ANIMAL_TYPE, COUNT(*) AS ANIMAL_COUNT
-- FROM ANIMAL_INS
-- WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
-- GROUP BY ANIMAL_TYPE
-- ORDER BY ANIMAL_TYPE ASC;

SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS ANIMAL_COUNT
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC;