-- select 절에서 column에 alias 붙이면
-- group by, order by 절에서 alias 로 사용이 가능하다.

/* SELECT HOUR(DATE_TIME) AS HOUR, COUNT(ANIMAL_ID) AS ANIMAL_COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATE_TIME) BETWEEN '09' AND '19'
GROUP BY HOUR
ORDER BY HOUR ASC; */ -- alias 가능

/* SELECT HOUR(DATE_TIME) AS HOUR, COUNT(ANIMAL_ID) AS ANIMAL_COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATE_TIME) BETWEEN '09' AND '19'
GROUP BY HOUR(DATE_TIME)
ORDER BY HOUR(DATE_TIME) ASC; */ -- 가능

SELECT HOUR(DATE_TIME) AS HOUR, COUNT(ANIMAL_ID) AS ANIMAL_COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR ASC;

-- dateformat() : %h 는 01-12 형식 / %H 는 00-23 형식

/* SELECT DATE_FORMAT(DATE_TIME, '%H') AS HOUR, COUNT(ANIMAL_ID) AS ANIMAL_COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATE_TIME, '%H:%s') BETWEEN '09:00' AND '19:59'
GROUP BY HOUR
ORDER BY HOUR ASC; */