-- CREATE TABLE ANIMAL_INS (
--    ANIMAL_ID VARCHAR(100),
--    ANIMAL_TYPE VARCHAR(100) NOT NULL,
--    DATE_TIME DATETIME NOT NULL,
--    INTAKE_CONDITION VARCHAR(100) NOT NULL,
--    ANIMAL_NAME VARCHAR(100),
--    SEX_UPON_INTAKE VARCHAR(100) NOT NULL,

--    CONSTRAINT ANIMAL_ID_PK PRIMARY KEY(ANIMAL_ID)       
-- );

-- CREATE TABLE ANIMAL_OUTS (
--    ANIMAL_ID VARCHAR(100),
--    ANIMAL_TYPE VARCHAR(100) NOT NULL,
--    DATE_TIME DATETIME NOT NULL,
--    ANIMAL_NAME VARCHAR(100),
--    SEX_UPON_INTAKE VARCHAR(100) NOT NULL,

--    CONSTRAINT ANIMAL_ID_FK
--    FOREIGN KEY (ANIMAL_ID)
--    REFERENCES ANIMAL_INS (ANIMAL_ID) ON UPDATE CASCADE
-- );

-- animal_outs table 기준으로 right (outer) join 하면
-- animal_outs table 의 animal_id 가 없는 경우에
-- animal_ins table 의 animal_id 의 값이 null 값이 된다.

SELECT ANIMAL_OUTS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_OUTS.ANIMAL_NAME AS ANIMAL_NAME
FROM ANIMAL_INS RIGHT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_OUTS.ANIMAL_ID ASC;