-- 날짜가 빠른 순서로 정렬하기: 날짜 오름차순
-- 최근일수록 날짜가 더 작다고 판단
-- (inner) join 은 animal_ins table 과 animal_outs table 의 교집합

SELECT ANIMAL_INS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_INS.ANIMAL_NAME AS ANIMAL_NAME
FROM ANIMAL_INS INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATE_TIME > ANIMAL_OUTS.DATE_TIME
ORDER BY ANIMAL_INS.DATE_TIME ASC;