SELECT ANIMAL_INS.ANIMAL_NAME AS ANIMAL_NAME, ANIMAL_INS.DATE_TIME AS DATE_TIME
FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_INS.DATE_TIME ASC
LIMIT 3;