-- 조인 사용하지 않고 서브쿼리 사용
SELECT ANIMAL_ID, ANIMAL_TYPE, ANIMAL_NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN
(SELECT ANIMAL_ID
 FROM ANIMAL_INS
 WHERE SEX_UPON_INTAKE LIKE '%Intact%')
AND (SEX_UPON_OUTCOME LIKE '%Spayed%' OR SEX_UPON_OUTCOME LIKE '%Neutered%')
ORDER BY ANIMAL_ID ASC;

-- 조인 사용
-- Regular Expression(정규표현식): regexp 사용(like 대신!)

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.ANIMAL_NAME
FROM ANIMAL_INS
    INNER JOIN ANIMAL_OUTS
    ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    -- ANIMAL_INS.ANIMAL_ID == ANIMAL_OUTS.ANIMAL_ID (X)
    -- sql 은 == 없습니다...
    -- ON (조건) 대신에 조인을 위한 column 명이 동일하다면
    -- USING(ANIMAL_ID) 가능
WHERE
    ANIMAL_INS.SEX_UPON_INTAKE LIKE 'Intact%'
    AND ANIMAL_OUTS.SEX_UPON_OUTCOME regexp 'Spayed|Neutered'
ORDER BY ANIMAL_INS.ANIMAL_ID ASC;
